# Generated by Django 3.1 on 2020-08-21 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birthDate', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(12)])),
                ('Photo', models.CharField(max_length=100)),
                ('whatsAppLink', models.CharField(max_length=100)),
                ('telegramLink', models.CharField(max_length=50)),
                ('instagramLink', models.CharField(max_length=50)),
                ('createDateTime', models.CharField(blank=True, max_length=20, null=True)),
                ('Status', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='WorkSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workSampleTitle', models.CharField(max_length=50)),
                ('workSampleFullDescriptions', models.CharField(max_length=300)),
                ('WorkSampleDoDate', models.CharField(max_length=20)),
                ('employerSpecifications', models.CharField(max_length=50)),
                ('gitLink', models.CharField(max_length=100)),
                ('createDateTime', models.CharField(blank=True, max_length=20, null=True)),
                ('Status', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1)])),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalSite_Application.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=50)),
                ('skillValue', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(3)])),
                ('createDateTime', models.CharField(blank=True, max_length=20, null=True)),
                ('Status', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1)])),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalSite_Application.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=50)),
                ('serviceDescriptions', models.CharField(max_length=200)),
                ('serviceOrder', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(3)])),
                ('createDateTime', models.CharField(blank=True, max_length=20, null=True)),
                ('Status', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1)])),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalSite_Application.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullnameSender', models.CharField(max_length=50)),
                ('emailSender', models.CharField(max_length=50)),
                ('phoneNumberSender', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(12)])),
                ('messageText', models.CharField(max_length=800)),
                ('createDateTime', models.CharField(blank=True, max_length=20, null=True)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalSite_Application.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutTitle', models.CharField(max_length=50)),
                ('aboutFullText', models.CharField(max_length=1000)),
                ('createDateTime', models.CharField(blank=True, max_length=20, null=True)),
                ('Status', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1)])),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalSite_Application.profile')),
            ],
        ),
    ]
