# Generated by Django 3.1 on 2020-08-31 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalSite_Application', '0004_auto_20200831_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesreceived',
            name='phoneNumberSender',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
