# Generated by Django 3.1 on 2020-08-31 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalSite_Application', '0005_auto_20200831_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesreceived',
            name='phoneNumberSender',
            field=models.BigIntegerField(validators=[django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
