# Generated by Django 3.1 on 2020-08-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalSite_Application', '0007_auto_20200831_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesreceived',
            name='phoneNumberSender',
            field=models.IntegerField(max_length=13),
        ),
    ]
