# Generated by Django 3.0.8 on 2020-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalSite_Application', '0009_auto_20200831_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesreceived',
            name='FullnameSender',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='messagesreceived',
            name='emailSender',
            field=models.CharField(max_length=150),
        ),
    ]
